trigger:
  branches:
    include:
      - dev

pool:
  name: 'Astro'

variables:
  nodeVersion: '24.x'

stages:
- stage: BuildFrontend 
  displayName: 'Build Frontend'
  jobs:
  - job: BuildFrontendJob
    displayName: 'Build Next.js App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'
    
    - task: DownloadSecureFile@1
      name: FrontendEnv
      inputs:
        secureFile: 'envex'
      displayName: 'Download Environment File'
    
    - script: |
        cp $(FrontendEnv.secureFilePath) .env
        echo "Building frontend application"
        npm install --legacy-peer-deps
        npm run build
      displayName: 'Build Frontend Application'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.ArtifactStagingDirectory)/calligadhfrontend.tar.gz'
        replaceExistingArchive: true
      displayName: 'Archive Frontend Files'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/calligadhfrontend.tar.gz'
        ArtifactName: 'frontend'
        publishLocation: 'Container'
      displayName: 'Publish Frontend Artifact'